# Generated by Django 5.1.3 on 2024-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metododepago',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
