# Generated by Django 5.1.3 on 2024-11-11 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en la que quieres agendar tu reserva')),
                ('estado', models.CharField(choices=[('confirmar', 'Confirmar'), ('cancelar', 'Cancelar')], max_length=20)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa.mesa')),
            ],
        ),
    ]
