# Generated by Django 5.1.3 on 2024-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_mesa', models.PositiveIntegerField(default=1)),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.TextField()),
            ],
        ),
    ]
