# Generated by Django 5.1.3 on 2024-11-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_pago', '0002_alter_metododepago_tipo'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='metodo_pago.metododepago'),
        ),
    ]
