# Generated by Django 5.1.3 on 2024-11-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='precio_unitario',
        ),
    ]
